# Generated by Django 6.1 on 2026-08-20 08:45

import shortener.apps.links.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("links", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="link",
            name="expired_at",
        ),
        migrations.AddField(
            model_name="link",
            name="expires_at",
            field=models.DateTimeField(default=shortener.apps.links.models.default_expiry),
        ),
    ]
